documentation setup
ZIB-IOL/Boscia.jl pull request #189
Opened 2024-05-22 13:43 UTC by saurabhintoml

2024-05-22 14:02 UTC, dhendryc requested changes

2024-06-11 19:11 UTC, matbesancon commented on Manifest.toml
> +# This file is machine-generated - editing it directly is not advised
the manifest file should not be committed

2024-06-11 19:12 UTC, matbesancon commented on LICENSE
> +Copyright (c) 2024 Saurabh Srivastava
You don't need to add individual contributors to the license file, they are kept in the git tracker instead

2024-06-11 19:12 UTC, matbesancon commented on README.md
> +The Boscia.jl solver uses a combination of a variant of the Frank-Wolfe algorithm and a branch-and-bound-like algorithm to solve mixed-integer convex optimization problems. These problems are of the
the sentence here is too verbose

2024-06-11 19:13 UTC, matbesancon commented on README.md
> +**min_{x ∈ C, x_I ∈ Z^n} f(x)**,
please revert the changes here on line 11 and 12, they are not necessary

2024-06-11 19:14 UTC, matbesancon commented on README.md
> +
```suggestion
```

2024-06-11 19:14 UTC, matbesancon commented on README.md
> +or alternatively you can do this
```suggestion
or alternatively via Pkg in any Julia code:
```

2024-06-11 19:15 UTC, matbesancon commented on README.md
> +If you don't have SCIP  , you can on go this link and add SCIP as instructed ['SCIP'](https://github.com/scipopt/SCIP.jl)
```suggestion
If you don't have SCIP, you can on go this link and add SCIP as instructed ['SCIP'](https://github.com/scipopt/SCIP.jl)
```

2024-06-11 19:15 UTC, matbesancon commented on README.md
> +**For Window Users** You need not to download whole SCIP binary instead you can follow **Custom Installation** mentioned on this page and download and link SCIP with your JULIA .
this is a bit too verbose, this is repeating the SCIP.jl readme

2024-06-11 19:16 UTC, matbesancon commented on README.md
> +
```suggestion
```
empty line not necessary

2024-06-11 19:16 UTC, matbesancon commented on examples/HiGHS_example.jl
> +# The final solution `x` and the result status are obtained using `Boscia.solve`.using Boscia
```suggestion
# The final solution `x` and the result status are obtained using `Boscia.solve`.using Boscia
```

the `using Boscia` part should be on a new line

2024-06-11 19:18 UTC, matbesancon commented on examples/approx_planted_point.jl
> +# This script tests different methods for solving optimization problems involving approximate planted points
I really like the addition of an introductory comment on the top of each example, but we should be a bit more concise for each of them. Anything that can be read from the code is not necessary. For instance 
> checks the solution against expected values, and verifies the correctness of  the results using `@test` assertions.

2024-06-19 12:48 UTC, dhendryc requested changes

2024-06-19 12:48 UTC, dhendryc commented on docs/src/basics.md
> +Boscia focuses on mixed-integer convex problems in which the nonlinear constraints and objectives are convex and presents a new algorithmic framework for solving these problems that exploit recent ad
Currently we only support linear constraints.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/basics.md
> +## BPCG
BPCG is the default but not the only variant that can be used. I would move this more back.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/basics.md
> +## Strong Branching
I would add that we have Hybrid branching which couples strong branching and most infeasible branching. Strong branching is very expensive to do for the whole tree and it's usually more beneficial to utilize strong branching only up to a certain depth.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/index.md
> +# Boscia.jl
We already have that in the `ReadMe` file.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/1_algorithms.md
> +# Algorithms
Algorithm 

Not Algorithms. Boscia is one algorithm with many options and settings.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/1_algorithms.md
> +This section contains information about interface.jl
In this section we present the algorithm interface and the possible settings.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/2_blmo_build.md
> +# LMO
The Bounded Linear Minimization Oracle (BLMO)

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/2_blmo_build.md
> +This section contains information about interface blmo_interface.jl , build_lmo.jl and time_tracking_lmo.jl
This section describes the general interface to the Bounded Linear Minimization Oracle and the preimplemented types of BLMO.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/2_blmo_build.md
> +## BLMO_Interface
General BLMO interface

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/2_blmo_build.md
> +## Time Tracking LMO
Time tracking wrapper

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/2_blmo_build.md
> +## Build LMO
Adapting the BLMO to the node problems

Also move that behind the Time Tracking LMO

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/2_blmo_build.md
> +```
Also, it's missing the `MOI oracle`, the `Managed_BLMO` and the `Polytopes`.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/custom.md
> +# CusBono IntBound Problem
The branch-and-bound tree functionality

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/custom.md
> +This section contain information about custom_bonobo.jl , integer_bounds.jl and problem.jl
This section contains the customization of the branch-and-bound implementation of Bonobo.jl.

We don't need the subsection here.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/fw_variant.md
> +# FW_variant
The Frank-Wolfe variants.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/fw_variant.md
> +This file contains information about all the frank_wolfe_variants.jl
Here is the list with the currently supported Frank-Wolfe variants.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/utilities.md
> +This section contain information about utilities.jl
This section contains some utility functionality.

2024-06-19 12:48 UTC, dhendryc commented on docs/src/reference/utilities.md
> +## utilities
Not necessary

2024-06-19 13:19 UTC, dhendryc requested changes

2024-06-19 13:19 UTC, dhendryc commented on docs/src/basics.md
> +Boscia focuses on mixed-integer convex problems in which the linear constraints and objectives are convex and presents a new algorithmic framework for solving these problems that exploit recent advan
constraints linear, objective nonlinear

2024-06-19 13:28 UTC, saurabhintoml commented on docs/src/basics.md
> +Frank-Wolfe methods produce primal feasible iterates and an FW gap, offering many inexpensive iterations with a gradually increasing dual bound. This allows early termination of nodes when the dual b
okay

2024-06-19 13:28 UTC, saurabhintoml commented on docs/src/basics.md
> +## BPCG
what to do in this

2024-06-19 13:29 UTC, saurabhintoml commented on examples/cube_blmo.jl
> +# 2. Necessary Functions:
okay

2024-06-19 14:40 UTC, matbesancon commented on .github/workflows/CI.yml
> +name: CI
you should merge with ci.yaml (small)

2024-06-19 16:40 UTC, matbesancon commented on LICENSE
> +Copyright (c) 2024 Saurabh Srivastava
@saurabhintoml still to remove?

2024-07-10 10:28 UTC, dhendryc requested changes
We don't need this file. Please merge it with the `ci.yml` file (in terms of contents).

2024-07-10 10:28 UTC, dhendryc commented on .github/workflows/CI.yml
We don't need this file. Please merge it contents with `ci.yml`.

2024-07-10 10:28 UTC, dhendryc commented on Manifest.toml
This should not be tracked. Please remove it from the git tracking list.

2024-07-10 10:28 UTC, dhendryc commented on README.md
> +If you don't have SCIP  , you can on go this link and add SCIP as instructed ['SCIP'](https://github.com/scipopt/SCIP.jl)
We don't have to explicitly state this.

2024-07-10 10:28 UTC, dhendryc commented on docs/make.jl
> +    format = Documenter.HTML(repolink = "https://github.com/saurabhintoml/Boscia.jl.git"),
The links have to be changed to the main Boscia repository, i.e. the ZIB-IOL/Boscia one.

2024-07-10 10:28 UTC, dhendryc commented on docs/src/basics.md
> +## BPCG
Move it further down the page and state that it is used as the default.

2024-07-10 10:28 UTC, dhendryc commented on docs/src/basics.md
> +Frank-Wolfe methods produce primal feasible iterates and an FW gap, offering many inexpensive iterations with a gradually increasing dual bound. This allows early termination of nodes when the dual b
Where is the explanation of the Frank-Wolfe gap?

2024-07-10 10:28 UTC, dhendryc commented on examples/mps-example.jl
> -using Boscia
We still need Boscia as a dependency

2024-07-10 10:28 UTC, dhendryc commented on examples/low_dim_in_high_dim.jl
> -using Boscia
We still need Boscia as a dependency.

2024-07-10 10:28 UTC, dhendryc commented on examples/lasso.jl
> -using Statistics
The example requires this package.

2024-08-13 11:54 UTC, merged